package com.itechart.courses.enums;

public enum RoleEnum {
    ROLE_RECEIVING_ORDERS_MANAGER,
    ROLE_PROCESSING_ORDERS_SPECIALIST,
    ROLE_SERVICE_DELIVERY_MANAGER,
    ROLE_SUPERVISOR,
    ROLE_ADMIN
}

